export const STATES = [
  "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir",
  "Jharkhand", "Karnataka", "Kerala", "Ladakh", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya",
  "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const ISSUES_MAP: Record<string, string> = {
  eviction: "Illegal eviction",
  deposit: "Deposit not returned",
  rent_hike: "Rent hike dispute",
  lockout: "Lockout / entry denial",
  agreement: "Agreement issues",
  maintenance: "Maintenance neglect",
};

export const GENERAL_RIGHTS: Record<string, { title: string; content: string; legal_reference: string; action: string }> = {
  eviction: {
    title: "Protection Against Arbitrary Eviction",
    content: "Under the Model Tenancy Act 2021 and Transfer of Property Act 1882, a landlord cannot evict a tenant without a valid ground (e.g., non-payment of rent for 2+ months, subletting without permission) and must give written notice. Forcible eviction without a court order is illegal and amounts to criminal trespass.",
    legal_reference: "Model Tenancy Act 2021 §21; Transfer of Property Act 1882 §106",
    action: "Send a legal notice demanding restoration of possession and pay your rent via bank transfer to create a documented record.",
  },
  deposit: {
    title: "Security Deposit Must Be Returned",
    content: "The Model Tenancy Act 2021 caps security deposit at 2 months rent (residential). The landlord must return the deposit within 1 month of vacating, after deducting only documented repair costs. Withholding without reason is actionable.",
    legal_reference: "Model Tenancy Act 2021 §11; Transfer of Property Act 1882 §108",
    action: "Send a demand notice via registered post. If unresolved in 30 days, file a complaint at the Rent Authority or Consumer Forum.",
  },
  rent_hike: {
    title: "Rent Cannot Be Increased Arbitrarily",
    content: "Rent can only be increased as per the terms agreed in the rental agreement. Under the Model Tenancy Act 2021, rent revision requires a written agreement. Any increase beyond the agreed terms without 3-months notice and written consent is invalid.",
    legal_reference: "Model Tenancy Act 2021 §7; Indian Contract Act 1872",
    action: "Refuse to pay the excess amount and send a legal notice citing your agreement terms. File at Rent Authority if landlord persists.",
  },
  lockout: {
    title: "Landlord Cannot Lock You Out",
    content: "Section 108(e) of the Transfer of Property Act gives tenants the right to peaceful possession. A landlord who cuts utilities, changes locks, or removes belongings is committing wrongful interference and can face criminal charges under IPC §441 (criminal trespass) and §503 (criminal intimidation).",
    legal_reference: "Transfer of Property Act §108(e); IPC §441, §503",
    action: "File an FIR at the local police station immediately. Simultaneously send a legal notice. Courts can grant mandatory injunction for restoration the same day.",
  },
  agreement: {
    title: "One-Sided Clauses Are Unenforceable",
    content: "Under the Indian Contract Act 1872, a contract term that is unconscionable (grossly unfair) or that violates a statutory right is void. Clauses that waive your right to notice before eviction, deny right to repairs, or impose arbitrary penalties are void ab initio.",
    legal_reference: "Indian Contract Act 1872 §23, §25; Model Tenancy Act 2021",
    action: "Do not sign agreements with blank spaces. Get a KiraDarbar Agreement Review (₹499) before signing to flag illegal clauses.",
  },
  maintenance: {
    title: "Landlord Must Maintain Habitable Conditions",
    content: "Under Section 108(b) of the Transfer of Property Act, the landlord must maintain the property in a condition fit for the purposes for which it was let. Tenants can deduct repair costs from rent (with notice) if the landlord fails to act within a reasonable time.",
    legal_reference: "Transfer of Property Act §108(b); Model Tenancy Act 2021 §13",
    action: "Send a written complaint via email/WhatsApp and give 30 days to repair. If unresolved, file at Rent Authority or Consumer Forum for compensation.",
  },
};

export const STATE_SPECIFIC_RIGHTS: Record<string, Partial<Record<string, { title: string; content: string; legal_reference: string; action: string }>>> = {
  "Maharashtra": {
    eviction: { title: "Maharashtra Rent Control Act: Strong Tenant Protection", content: "Under the Maharashtra Rent Control Act 1999, a landlord can evict only on specific grounds: non-payment of rent for 6+ months, subletting, bona fide personal use, or irreparable damage. A court order is mandatory before eviction. Self-help eviction is a criminal offense punishable with imprisonment under §28.", legal_reference: "Maharashtra Rent Control Act 1999 §16, §28", action: "File an application before the Court of Small Causes (Mumbai) or Civil Court if served an eviction notice without proper grounds." },
    deposit: { title: "Deposit Limited to 3 Months Rent", content: "In Maharashtra, landlords typically take 2–3 months rent as deposit. The Maharashtra Rent Control Act requires the deposit to be returned within a reasonable time after vacation, net of documented deductions. Withholding is actionable before the Rent Court.", legal_reference: "Maharashtra Rent Control Act 1999 §10; MTA 2021 §11", action: "Send a registered demand notice. File at the Court of Small Causes or District Consumer Disputes Redressal Commission." },
    rent_hike: { title: "Rent Increase Restricted to 4% PA for Protected Premises", content: "For premises under the Maharashtra Rent Control Act, rent increase is capped at 4% per annum. Rent above this requires landlord's application to the Rent Court. New leases post-1999 are governed by MRC Act §4.", legal_reference: "Maharashtra Rent Control Act 1999 §4, §11A", action: "Challenge any increase above 4% PA by filing an application before the Rent Controller." },
    lockout: { title: "Lockout is a Cognizable Offense in Maharashtra", content: "Maharashtra Police Act §135 and IPC §441 make wrongful confinement and criminal trespass cognizable offenses. Police must register an FIR on a tenant lockout complaint. Courts have consistently granted same-day injunctions in Mumbai and Pune.", legal_reference: "Maharashtra Rent Control Act 1999 §28; IPC §441; Maharashtra Police Act §135", action: "File FIR at local police station immediately. Apply for urgent injunction at City Civil Court or Small Causes Court." },
    maintenance: { title: "Landlord Liable for Structural Repairs", content: "Under the Maharashtra Rent Control Act §29, tenants can carry out urgent repairs and recover costs from landlord if the landlord fails to act after a 15-day written notice. The Rent Court can order landlords to carry out repairs.", legal_reference: "Maharashtra Rent Control Act 1999 §29", action: "Give 15-day written notice for repairs. If ignored, carry out repairs and recover costs or file application before Rent Court." },
  },
  "Delhi": {
    eviction: { title: "Delhi Rent Control Act: Wide Protection", content: "The Delhi Rent Control Act 1958 applies to premises with rent up to ₹3,500/month. Landlords need a court decree for eviction; grounds are strictly limited (non-payment, subletting, bona fide need, etc.). The Rent Controller must approve all evictions.", legal_reference: "Delhi Rent Control Act 1958 §14; Model Tenancy Act 2021", action: "If your rent is above ₹3,500/month, the MTA 2021 applies. Challenge eviction before Rent Controller or District Court." },
    deposit: { title: "No Statutory Cap — Rely on Agreement and MTA", content: "Delhi does not have a statutory deposit cap for high-rent premises. The Model Tenancy Act 2021 (applicable to new agreements) caps it at 2 months. File complaint at Rent Authority if deposit is withheld beyond 1 month of vacating.", legal_reference: "Delhi Rent Control Act 1958; Model Tenancy Act 2021 §11", action: "File complaint at Rent Authority of Delhi (Tis Hazari Courts) or Consumer Forum West/East Delhi." },
    rent_hike: { title: "Standard Rent Applies for DRC Premises", content: "For premises under the Delhi Rent Control Act, the 'standard rent' is fixed and cannot be exceeded. For newer agreements, rent increase must be agreed in writing. Unilateral increase is challengeable before the Rent Controller.", legal_reference: "Delhi Rent Control Act 1958 §10, §12", action: "Apply to the Rent Controller to fix or determine standard rent if your landlord is charging above the legal limit." },
    lockout: { title: "Police Must Act on Lockout Complaints in Delhi", content: "Delhi Police Standing Order 310 mandates registration of FIR for unlawful dispossession. In addition, tenants can file an urgent writ petition before the Delhi High Court for restoration of possession within hours.", legal_reference: "IPC §441; Delhi Rent Control Act 1958 §14(1)(a)", action: "File FIR at local police. Apply for urgent injunction at District Court. Delhi HC has restored possession same-day in urgent cases." },
    maintenance: { title: "Standard of Repair Must Be Maintained", content: "Delhi Rent Control Act §29 requires landlords to keep premises in good repair. Tenants may apply to the Rent Controller, who can direct the landlord to carry out repairs within a specified period. Failure to comply is contempt of court.", legal_reference: "Delhi Rent Control Act 1958 §29, §30", action: "Apply to Rent Controller for a repair direction order after giving written notice and waiting 30 days." },
  },
  "Karnataka": {
    eviction: { title: "Karnataka Rent Act: Notice + Court Order Required", content: "The Karnataka Rent Act 2001 requires landlords to issue a written eviction notice and obtain a court decree. Grounds include non-payment for 3 months, subletting without consent, breach of conditions, or bona fide requirement. Forceful eviction without court order is a criminal offense.", legal_reference: "Karnataka Rent Act 2001 §27, §28", action: "Challenge the eviction notice before the Rent Controller (designated Civil Court) in your jurisdiction." },
    deposit: { title: "Deposit Return Governed by Agreement and Karnataka Rent Act", content: "The Karnataka Rent Act requires landlords to return the advance/deposit within 30 days of vacation after deducting legitimately documented damages. Unilateral deductions are challengeable before the Rent Authority.", legal_reference: "Karnataka Rent Act 2001 §4; MTA 2021 §11", action: "Send demand notice via RPAD. File complaint before Rent Authority or Consumer Forum in Bengaluru/Mysuru." },
    rent_hike: { title: "Rent Increase: 10% PA Cap for Controlled Premises", content: "Under the Karnataka Rent Act, for controlled premises, rent can increase by a maximum of 10% per annum. For newer agreements following MTA 2021, increase must be per written agreement terms.", legal_reference: "Karnataka Rent Act 2001 §5, §21", action: "Challenge excess rent hike before Rent Controller. Deposit the 'admitted' rent in court to protect your possession." },
    lockout: { title: "Lockout is Criminal Trespass Under Karnataka Law", content: "Karnataka courts have consistently held that changing locks or cutting utilities amounts to criminal trespass under IPC §441 and forceful dispossession under KPDL. Tenants can get police intervention and civil injunctions.", legal_reference: "Karnataka Rent Act 2001 §32; IPC §441; KPDL 1964", action: "Lodge FIR at local police station. Apply for urgent injunction at Civil Court/Rent Court. Karnataka HC has fast-track mechanisms." },
    maintenance: { title: "Repairs Are Landlord's Responsibility in Karnataka", content: "The landlord is responsible for maintaining the structure and essential services. Under Karnataka Rent Act §13, tenants can serve notice requiring repairs and, after 15 days, carry out urgent repairs themselves and deduct from rent.", legal_reference: "Karnataka Rent Act 2001 §13, §14", action: "Send written repair notice. If no action in 15 days, carry out repairs and deduct from rent (keep all receipts as evidence)." },
  },
  "Tamil Nadu": {
    eviction: { title: "Tamil Nadu Regulation of Rights & Responsibilities of Landlords and Tenants Act 2017", content: "TN's 2017 Act requires all tenancies to be registered through a Rent Authority. Eviction without a Rent Court order is prohibited. Grounds are limited: non-payment, subletting, bona fide need, or misuse of premises. Unregistered tenancies still have protection under general property law.", legal_reference: "TN Regulation of Landlords and Tenants Act 2017 §21; IPC §441", action: "Register your tenancy on the Tamil Nadu Rent Authority portal. Challenge eviction before the Rent Court in Chennai/Coimbatore/Madurai." },
    deposit: { title: "Advance Limited to 2 Months Rent under TN Act", content: "The Tamil Nadu 2017 Act caps advance rent at 2 months for residential premises. Landlords must refund within 1 month of vacation. Any deductions must be with written justification and receipts.", legal_reference: "TN Regulation of Landlords and Tenants Act 2017 §11", action: "File complaint before Rent Authority. If no response in 30 days, escalate to Rent Court." },
    rent_hike: { title: "Rent Revision Only Per Agreement Terms", content: "Under the TN 2017 Act, rent can only be revised as agreed in the registered tenancy agreement. Landlords cannot unilaterally increase rent before the term ends. Any revision must be through a supplementary registered agreement.", legal_reference: "TN Regulation of Landlords and Tenants Act 2017 §7", action: "Refuse excess rent payment. File at Rent Authority. Continue paying agreed rent via bank transfer." },
    lockout: { title: "Lockout is Strict Offense under TN Law", content: "The TN 2017 Act §26 specifically prohibits landlords from cutting essential services (water, electricity) or forcibly evicting without a court order. Violations attract fine and imprisonment up to 6 months.", legal_reference: "TN Regulation of Landlords and Tenants Act 2017 §26", action: "Lodge FIR citing TN Act §26. Apply for urgent mandamus before the Rent Court. TN courts take this seriously." },
    maintenance: { title: "Essential Services Cannot Be Disrupted by Landlord", content: "TN Act §26 and Transfer of Property Act §108(b) together make landlords responsible for maintaining essential services and structural integrity. Tenants can claim compensation for uninhabitable conditions.", legal_reference: "TN Regulation of Landlords and Tenants Act 2017 §26; TPA §108(b)", action: "Send documented complaint (email + WhatsApp screenshot). File at Rent Authority demanding repair order." },
  },
  "Telangana": {
    eviction: { title: "Telangana Tenancies Act: Grounds-Based Eviction Only", content: "Telangana follows the erstwhile AP Buildings (Lease, Rent and Eviction) Control Act 1960 until updated. Eviction requires court order on valid grounds: 6 months arrears, wilful damage, or bona fide owner occupation. Forceful eviction is punishable under IPC §441.", legal_reference: "AP Buildings (Lease, Rent & Eviction) Control Act 1960 §10; IPC §441", action: "File response before Rent Controller if served eviction petition. Challenge unlawful eviction at District Court, Hyderabad." },
    deposit: { title: "Advance Must Be Returned After Deduction of Legitimate Claims", content: "Telangana practice typically involves 10 months advance (especially Hyderabad). The Transfer of Property Act and Model Tenancy Act require refund after documented deductions within 1 month of vacation. Any withholding without reasons is challengeable.", legal_reference: "Transfer of Property Act §108; Model Tenancy Act 2021 §11", action: "Demand refund via RPAD notice. File at Rent Authority/Consumer Forum (City Consumer Forum, Hyderabad)." },
    rent_hike: { title: "Rent Hike Only If Contractually Allowed", content: "In Telangana, rent increase must strictly follow the lease agreement. For older properties under the AP Rent Control Act, standard rent rules apply. Unilateral hike is unenforceable in court.", legal_reference: "AP Buildings Control Act 1960 §6; Indian Contract Act §23", action: "Pay only agreed rent via bank transfer. File at Rent Controller's court challenging the hike." },
    lockout: { title: "Police Intervention is Available for Lockouts in Hyderabad", content: "Hyderabad Police Commissionerate has a dedicated grievance mechanism for tenant lockouts. IPC §441 and AP Rent Control Act §10 together provide grounds for FIR and civil injunction.", legal_reference: "AP Buildings Control Act 1960 §10; IPC §441; TS Police Act", action: "File online FIR on Telangana Police portal (www.tspolice.gov.in). Apply for urgent stay at District Court." },
    maintenance: { title: "Landlord Responsible for Structural and Essential Repairs", content: "The TPA §108(b) and AP Buildings Control Act both impose maintenance obligations on landlords. Tenants can approach the Rent Controller for a direction to maintain premises.", legal_reference: "AP Buildings Control Act 1960; TPA §108(b)", action: "Give 30-day written notice. If ignored, file complaint at Rent Authority or Consumer Forum for compensation." },
  },
  "Gujarat": {
    eviction: { title: "Gujarat Rent Control Act: Formal Eviction Process Mandatory", content: "Under the Gujarat Rent Control Act 1947, no tenant can be evicted except by an order of the Rent Controller. Grounds are: non-payment, nuisance, subletting, or bona fide landlord need. Premises with rent above ₹3,500/month require Civil Court order.", legal_reference: "Gujarat Rent Control Act 1947 §13, §28", action: "Challenge any eviction before the Rent Controller in your city (Ahmedabad, Surat, Vadodara, etc.)." },
    deposit: { title: "Advance Refund Governed by Contract and MTA", content: "Gujarat practice varies by city (Ahmedabad typically 10–12 months advance in some areas). The MTA 2021 caps new agreements at 2 months. Refund must be made within 1 month of vacating. Consumer Forum regularly awards compensation for wrongful withholding.", legal_reference: "Model Tenancy Act 2021 §11; Consumer Protection Act 2019", action: "Send demand notice. File at District Consumer Disputes Redressal Commission in Ahmedabad/Surat." },
    rent_hike: { title: "Rent Settled by Rent Controller if Disputed", content: "The Gujarat Rent Control Act allows both parties to approach the Rent Controller to determine standard rent. Unilateral hike by landlord cannot be enforced without Rent Controller's order.", legal_reference: "Gujarat Rent Control Act 1947 §5, §9", action: "Apply to Rent Controller for standard rent determination. Pay rent under protest in the interim to avoid eviction." },
    lockout: { title: "Lockout — IPC § 441 Applies; file FIR Immediately", content: "Gujarat Police guidelines require registration of FIR for unlawful eviction/lockout. The Gujarat Rent Control Act §28 also provides criminal penalties for landlords who evict without court order.", legal_reference: "Gujarat Rent Control Act 1947 §28; IPC §441", action: "File FIR at local police station. Apply for urgent injunction at Civil Court with key evidence (photos, video, witnesses)." },
    maintenance: { title: "Landlord Must Maintain the Property", content: "TPA §108(b) and Gujarat Rent Control Act impose duty on landlord to keep property habitable. Tenants can file application before Rent Controller for a repair order.", legal_reference: "Gujarat Rent Control Act 1947; TPA §108(b)", action: "Give 30-day written repair notice. File application before Rent Controller for mandatory repair order." },
  },
  "Rajasthan": {
    eviction: { title: "Rajasthan Rent Control Act 2001: Court Order Mandatory", content: "The Rajasthan Rent Control Act 2001 requires a Rent Tribunal order for eviction. Grounds: non-payment of 3+ months rent, subletting, bona fide personal use. Unregistered agreements still receive protection under TPA 1882.", legal_reference: "Rajasthan Rent Control Act 2001 §14, §23", action: "Appear before Rent Tribunal (Jaipur/Jodhpur/Kota) if served eviction notice. Challenge procedural defects to buy time." },
    deposit: { title: "Security Deposit Return within 1 Month of Vacation", content: "Under MTA 2021 (for new agreements), deposit is capped at 2 months. For older agreements, the contractual amount applies. Landlord must return within 30 days with written deduction details or face civil liability.", legal_reference: "Model Tenancy Act 2021 §11; Rajasthan Rent Control Act 2001", action: "Send RPAD notice. File at District Consumer Forum in Jaipur/Jodhpur if unresolved in 30 days." },
    rent_hike: { title: "Tenancy Terms Govern Rent Increase", content: "Under Rajasthan RC Act 2001, rent increase beyond what is agreed is challengeable before the Rent Tribunal. Standard rent can be determined by the Tribunal on application.", legal_reference: "Rajasthan Rent Control Act 2001 §5, §8", action: "File application at Rent Tribunal for standard rent fixation if facing excessive hike." },
    lockout: { title: "Police Protection Available Against Lockouts in Rajasthan", content: "Rajasthan Police have jurisdiction to intervene in tenant lockout cases under IPC §441 and §503. Tenants can approach Superintendent of Police or DCP directly if local police are unresponsive.", legal_reference: "IPC §441; Rajasthan Police Act; Rajasthan RC Act 2001 §23", action: "File FIR. If police don't act, approach SP/DCP. File urgent writ at Rajasthan High Court (Jodhpur) or bench at Jaipur." },
    maintenance: { title: "Landlord Must Keep Property Habitable", content: "TPA §108(b) and Rajasthan RC Act together require landlords to maintain premises. Courts can pass mandatory injunctions requiring landlords to carry out specific repairs.", legal_reference: "Rajasthan Rent Control Act 2001; TPA §108(b)", action: "Give 30-day written notice. File complaint at Rent Tribunal for mandatory repair direction." },
  },
  "Uttar Pradesh": {
    eviction: { title: "UP Urban Buildings Regulation Act: Very Strong Tenant Protection", content: "The UP Urban Buildings (Regulation of Letting, Rent & Eviction) Act 1972 heavily protects tenants in specified buildings. Eviction only by Prescribed Authority order on listed grounds. Unauthorized eviction is a criminal offense under §27.", legal_reference: "UP Urban Buildings Act 1972 §20, §27", action: "If you are in a 'regulated building', challenge eviction before the Prescribed Authority (SDM/Rent Controller) in your district." },
    deposit: { title: "Advance Rent Regulated Under UP Act", content: "The UP Urban Buildings Act §20(2) prohibits taking more than 1 month's advance for regulated buildings. Excess advance is recoverable. MTA 2021 applies to unregulated buildings (post-1985 construction), capping at 2 months.", legal_reference: "UP Urban Buildings Act 1972 §20(2); MTA 2021 §11", action: "File complaint before Prescribed Authority (SDM) for excess advance recovery or withheld deposit." },
    rent_hike: { title: "Rent Fixed by Rent Act — Cannot Exceed Authorized Amount", content: "For buildings under UP Urban Buildings Act, the authorized rent is determined by the Prescribed Authority. No landlord can charge beyond this. For unregulated buildings, contract terms govern.", legal_reference: "UP Urban Buildings Act 1972 §4, §9", action: "Apply to Prescribed Authority (SDM) for determination of authorized rent." },
    lockout: { title: "UP Act §27 — Criminal Penalty for Wrongful Eviction", content: "Section 27 of the UP Urban Buildings Act makes any person who causes or attempts to cause wrongful eviction liable to imprisonment up to 3 years or fine. Police must file FIR under this provision.", legal_reference: "UP Urban Buildings Act 1972 §27; IPC §441", action: "File FIR citing §27 of UP Urban Buildings Act. Approach Prescribed Authority for immediate restoration order." },
    maintenance: { title: "Landlord Responsible Under UP Act", content: "The UP Act and TPA §108(b) together impose repair obligations. Courts in UP have granted rent abatement (reduction) for uninhabitable conditions.", legal_reference: "UP Urban Buildings Act 1972; TPA §108(b)", action: "Give written notice. Apply to Prescribed Authority for repair order or rent abatement." },
  },
  "West Bengal": {
    eviction: { title: "West Bengal Premises Tenancy Act: Court Decree Mandatory", content: "The West Bengal Premises Tenancy Act 1997 prohibits eviction without a court decree. Grounds: arrears of rent for 2+ months, unlawful subletting, bona fide requirement, or irreparable damage. Tenants have strong protection even against landlords who prove bona fide need.", legal_reference: "WB Premises Tenancy Act 1997 §5, §24", action: "Contest eviction before the Civil Court (2nd or Munsiff Court) in Kolkata/Howrah/Siliguri. File written objection within 30 days of notice." },
    deposit: { title: "Advance Return Governed by WB Act and Contract", content: "Under WB Premises Tenancy Act, any advance or deposit must be returned after deducting only legitimately documented damages. Delay beyond 1 month without reason is actionable before Civil Court.", legal_reference: "WB Premises Tenancy Act 1997; MTA 2021 §11", action: "Send RPAD notice. File at Civil Court (Original Side) or Consumer Forum in Kolkata." },
    rent_hike: { title: "Rent Enhancement by Application to Rent Controller", content: "WB Tenancy Act allows landlords to apply for enhanced rent after specific periods. Unilateral increase without court approval is unenforceable. Tenants can challenge any such increase before the Rent Controller.", legal_reference: "WB Premises Tenancy Act 1997 §9, §10", action: "File objection before Rent Controller within 2 months of receiving enhanced rent demand." },
    lockout: { title: "Section 14 WB Act — Landlord Cannot Withhold Access", content: "WB Premises Tenancy Act §14 specifically prohibits interference with lawful possession. Cutting utilities, changing locks, or removing tenant's goods is an offense under the Act and IPC §441.", legal_reference: "WB Premises Tenancy Act 1997 §14; IPC §441", action: "File FIR at local police. Apply to the Civil Court for mandatory injunction for restoration of possession." },
    maintenance: { title: "Landlord Duty: Structural and Essential Repairs", content: "Under WB Premises Tenancy Act §15, landlords must maintain the structure and essential services. Tenants can apply to the Controller for an order directing repairs. Tenants may also carry out urgent repairs and recover costs.", legal_reference: "WB Premises Tenancy Act 1997 §15, §16", action: "File application before Rent Controller for repair direction. Keep all repair demand communications as evidence." },
  },
};

export function getRightsForStateAndIssue(state: string, issue: string) {
  const stateData = STATE_SPECIFIC_RIGHTS[state];
  if (stateData && stateData[issue]) {
    return stateData[issue]!;
  }
  return GENERAL_RIGHTS[issue];
}
